###Get All Posts
GET  http://localhost:8081/v1/content/


###Create Post


POST  http://localhost:8081/v1/content/create
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2MzBhNDJmN2JhZjcyOGE1NWFlN2JiOTgiLCJpYXQiOjE2NjE2MjkzOTksInR5cGUiOiJhY2Nlc3MifQ.H2WCSTZcBWKJyc9B2tL8z79BuPPpsOxAV75FNFs5Nv0

{
	"userId":"630a42f7baf728a55ae7bb98",
	"body": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum."
}